// src/lib/export/pptx/pptxExporter.ts
// PowerPoint export using PptxGenJS with layout adapters

import pptxgen from 'pptxgenjs';
import { getAdapter } from './adapters';
import { PresentationData, ColorPalette, SLIDE_WIDTH, SLIDE_HEIGHT, toHex } from './types';
import { ExportProgressCallback } from '../types';

// Default color palette if none provided
const DEFAULT_COLORS: ColorPalette = {
    primary: '#2563EB',
    secondary: '#7C3AED',
    accent: '#2563EB',
    bg: '#FFFFFF',
    text: '#0F172A',
};

// Helper: Get logo coordinates based on position and size
const getLogoPosition = (position: string, size: string) => {
    let x = 0.5;
    let y = 0.5;
    let w = 1.0;
    let h = 1.0;

    // Size
    switch (size) {
        case 'small': w = 0.8; h = 0.8; break;
        case 'large': w = 1.5; h = 1.5; break;
        case 'medium': default: w = 1.2; h = 1.2; break;
    }

    // Position
    switch (position) {
        case 'top-right': x = SLIDE_WIDTH - w - 0.5; y = 0.3; break;
        case 'bottom-left': x = 0.5; y = SLIDE_HEIGHT - h - 0.3; break;
        case 'bottom-right': x = SLIDE_WIDTH - w - 0.5; y = SLIDE_HEIGHT - h - 0.3; break;
        case 'top-left': default: x = 0.5; y = 0.3; break;
    }

    return { x, y, w, h };
};

/**
 * Export presentation to PowerPoint format
 * 
 * @param presentation - Presentation data including slides and theme
 * @param onProgress - Optional progress callback
 */
export const exportToPPTX = async (
    presentation: PresentationData,
    onProgress?: ExportProgressCallback
): Promise<void> => {
    if (!presentation.slides || presentation.slides.length === 0) {
        throw new Error('No slides to export');
    }

    const mainSlides = presentation.slides.filter((s: any) => !s.isAppendix) || [];
    const appendixSlides = presentation.slides.filter((s: any) => s.isAppendix) || [];
    const processedSlides = appendixSlides.length > 0
        ? [...mainSlides, { isSeparator: true, id: 'appendix-separator', title: 'Appendix', type: 'section-divider', layout: 'section-divider' }, ...appendixSlides]
        : mainSlides;

    onProgress?.({
        current: 0,
        total: processedSlides.length,
        status: 'preparing',
        message: 'Initialisation du PowerPoint...',
    });

    // Create new presentation
    const pptx = new pptxgen();

    // Set presentation properties
    pptx.author = 'SlideAI';
    pptx.title = presentation.title || 'Presentation';
    pptx.subject = 'Generated by SlideAI';
    pptx.company = 'SlideAI';

    // Define 16:9 layout
    pptx.defineLayout({
        name: 'SLIDEAI_16x9',
        width: SLIDE_WIDTH,
        height: SLIDE_HEIGHT,
    });
    pptx.layout = 'SLIDEAI_16x9';

    // Get color palette
    const colors = presentation.colorScheme || DEFAULT_COLORS;

    // Process each slide
    for (let i = 0; i < processedSlides.length; i++) {
        const slideData = processedSlides[i];

        onProgress?.({
            current: i,
            total: processedSlides.length,
            status: 'rendering',
            message: `Création de la slide ${i + 1}/${processedSlides.length}...`,
        });

        // Create new slide
        const pptxSlide = pptx.addSlide();

        // Get appropriate adapter
        const adapter = getAdapter(slideData);

        // Render slide using adapter
        try {
            await adapter.render(slideData, pptxSlide, colors, pptx);
        } catch (error) {
            console.error(`Error rendering slide ${i + 1}:`, error);
            // Add error placeholder
            pptxSlide.background = { color: 'FFFFFF' };
            pptxSlide.addText(`Erreur lors du rendu de la slide "${slideData.title || i + 1}"`, {
                x: 1,
                y: 3,
                w: SLIDE_WIDTH - 2,
                h: 1,
                fontSize: 24,
                fontFace: 'Arial',
                color: 'FF0000',
                align: 'center',
            });
        }

        // === CUSTOM TEMPLATE ELEMENTS ===
        if (presentation.templateOverlay) {
            const { logo, footer } = presentation.templateOverlay;
            const isCover = i === 0 || slideData.layout === 'cover';

            // 1. Logo Overlay
            if (logo && presentation.brandLogoUrl) {
                const shouldShow = isCover ? logo.showOnCover : logo.showOnContent;
                if (shouldShow) {
                    const { x, y, w, h } = getLogoPosition(logo.position, logo.size);
                    pptxSlide.addImage({
                        path: presentation.brandLogoUrl,
                        x, y, w, h
                    });
                }
            }

            // 2. Footer Overlay
            if (footer) {
                // Footer Text
                if (footer.text) {
                    pptxSlide.addText(footer.text, {
                        x: 0.5,
                        y: SLIDE_HEIGHT - 0.5,
                        w: SLIDE_WIDTH * 0.6,
                        h: 0.3,
                        fontSize: 10,
                        fontFace: 'Arial',
                        color: toHex(colors.text), // Use text color, maybe opacity?
                        transparency: 50,
                        align: 'left',
                    });
                }

                // Page Number (Override default if configured)
                if (footer.showPageNumber) {
                    pptxSlide.addText(String(i + 1), {
                        x: SLIDE_WIDTH - 0.8,
                        y: SLIDE_HEIGHT - 0.5,
                        w: 0.5,
                        h: 0.3,
                        fontSize: 10,
                        fontFace: 'Arial',
                        color: toHex(colors.text),
                        align: 'right',
                    });
                }
            } else {
                // Default page number if no footer config
                pptxSlide.addText(String(i + 1), {
                    x: SLIDE_WIDTH - 0.8,
                    y: SLIDE_HEIGHT - 0.5,
                    w: 0.5,
                    h: 0.3,
                    fontSize: 10,
                    fontFace: 'Arial',
                    color: toHex(colors.text),
                    align: 'right',
                });
            }
        } else {
            // Default page number logic (fallback)
            pptxSlide.addText(String(i + 1), {
                x: SLIDE_WIDTH - 0.8,
                y: SLIDE_HEIGHT - 0.5,
                w: 0.5,
                h: 0.3,
                fontSize: 10,
                fontFace: 'Arial',
                color: toHex(colors.text),
                align: 'right',
            });
        }
    }

    onProgress?.({
        current: processedSlides.length,
        total: processedSlides.length,
        status: 'generating',
        message: 'Génération du fichier PowerPoint...',
    });

    // Sanitize filename
    const sanitizedTitle = (presentation.title || 'presentation')
        .replace(/[^a-zA-Z0-9-_\s]/g, '')
        .trim();

    // Download file
    await pptx.writeFile({ fileName: `${sanitizedTitle}.pptx` });

    onProgress?.({
        current: processedSlides.length,
        total: processedSlides.length,
        status: 'complete',
        message: 'Export terminé !',
    });
};
