// src/lib/export/pptx/pptxExporter.ts
// PowerPoint export using PptxGenJS with layout adapters

import pptxgen from 'pptxgenjs';
import { getAdapter } from './adapters';
import { PresentationData, ColorPalette, SLIDE_WIDTH, SLIDE_HEIGHT, toHex } from './types';
import { ExportProgressCallback } from '../types';
import { buildEditableSlideScene } from './scene/builders';
import { renderSceneToPptx } from './scene/renderScene';

// Default color palette if none provided
const DEFAULT_COLORS: ColorPalette = {
    primary: '#2563EB',
    secondary: '#7C3AED',
    accent: '#2563EB',
    bg: '#FFFFFF',
    text: '#0F172A',
};

// Helper: Get logo coordinates based on position and size
const getLogoPosition = (position: string, size: string) => {
    let x = 0.5;
    let y = 0.5;
    let w = 1.0;
    let h = 1.0;

    // Size
    switch (size) {
        case 'small': w = 0.8; h = 0.8; break;
        case 'large': w = 1.5; h = 1.5; break;
        case 'medium': default: w = 1.2; h = 1.2; break;
    }

    // Position
    switch (position) {
        case 'top-right': x = SLIDE_WIDTH - w - 0.5; y = 0.3; break;
        case 'bottom-left': x = 0.5; y = SLIDE_HEIGHT - h - 0.3; break;
        case 'bottom-right': x = SLIDE_WIDTH - w - 0.5; y = SLIDE_HEIGHT - h - 0.3; break;
        case 'top-left': default: x = 0.5; y = 0.3; break;
    }

    return { x, y, w, h };
};

const addBaseSlideFooter = (
    pptxSlide: pptxgen.Slide,
    slideTitle: string,
    slideNumber: number,
    showPageNumber: boolean,
    colors: ColorPalette
) => {
    const primary = toHex(colors.primary || DEFAULT_COLORS.primary);
    const text = toHex(colors.text || DEFAULT_COLORS.text);

    pptxSlide.addShape('line', {
        x: 0.45,
        y: SLIDE_HEIGHT - 0.56,
        w: SLIDE_WIDTH - 0.9,
        h: 0,
        line: {
            color: primary,
            transparency: 80,
            width: 0.6,
        },
    });

    if (showPageNumber) {
        pptxSlide.addText(String(slideNumber), {
            x: 0.48,
            y: SLIDE_HEIGHT - 0.42,
            w: 0.45,
            h: 0.18,
            fontSize: 11,
            fontFace: 'Arial',
            bold: true,
            color: primary,
            align: 'left',
            margin: 0,
        });
    }

    if (slideTitle) {
        pptxSlide.addText(slideTitle, {
            x: 4.3,
            y: SLIDE_HEIGHT - 0.43,
            w: 4.7,
            h: 0.18,
            fontSize: 9.5,
            fontFace: 'Arial',
            color: text,
            transparency: 38,
            align: 'center',
            margin: 0,
            fit: 'shrink',
        });
    }

    pptxSlide.addText('2025', {
        x: SLIDE_WIDTH - 0.9,
        y: SLIDE_HEIGHT - 0.42,
        w: 0.42,
        h: 0.18,
        fontSize: 10.5,
        fontFace: 'Arial',
        color: text,
        transparency: 46,
        align: 'right',
        margin: 0,
    });
};

/**
 * Export presentation to PowerPoint format
 * 
 * @param presentation - Presentation data including slides and theme
 * @param onProgress - Optional progress callback
 */
export const exportToPPTX = async (
    presentation: PresentationData,
    slideElements?: HTMLElement[],
    onProgress?: ExportProgressCallback
): Promise<void> => {
    if (!presentation.slides || presentation.slides.length === 0) {
        throw new Error('No slides to export');
    }

    const mainSlides = presentation.slides.filter((s: any) => !s.isAppendix) || [];
    const appendixSlides = presentation.slides.filter((s: any) => s.isAppendix) || [];
    const processedSlides = appendixSlides.length > 0
        ? [...mainSlides, { isSeparator: true, id: 'appendix-separator', title: 'Appendix', type: 'section-divider', layout: 'section-divider' }, ...appendixSlides]
        : mainSlides;

    onProgress?.({
        current: 0,
        total: processedSlides.length,
        status: 'preparing',
        message: 'Initialisation du PowerPoint...',
    });

    // Create new presentation
    const pptx = new pptxgen();

    // Set presentation properties
    pptx.author = 'SlideAI';
    pptx.title = presentation.title || 'Presentation';
    pptx.subject = 'Generated by SlideAI';
    pptx.company = 'SlideAI';

    // Define 16:9 layout
    pptx.defineLayout({
        name: 'SLIDEAI_16x9',
        width: SLIDE_WIDTH,
        height: SLIDE_HEIGHT,
    });
    pptx.layout = 'SLIDEAI_16x9';

    // Get color palette
    const colors = presentation.colorScheme || DEFAULT_COLORS;

    // Process each slide
    for (let i = 0; i < processedSlides.length; i++) {
        const slideData = processedSlides[i];
        const slideElement = slideElements?.[i];
        const sceneMetaElement = slideElement?.matches?.('[data-export-family]')
            ? slideElement
            : slideElement?.querySelector?.('[data-export-family]');
        const forcedLayout = sceneMetaElement
            ? {
                family: sceneMetaElement.getAttribute('data-export-family') || undefined,
                variation: sceneMetaElement.getAttribute('data-export-variation') || undefined,
            }
            : undefined;

        onProgress?.({
            current: i,
            total: processedSlides.length,
            status: 'rendering',
            message: `Création de la slide ${i + 1}/${processedSlides.length}...`,
        });

        // Create new slide
        const pptxSlide = pptx.addSlide();

        let renderedAsFallbackImage = false;
        const sceneResult = buildEditableSlideScene(slideData, presentation, colors, forcedLayout);

        try {
            if (sceneResult.supported && sceneResult.scene) {
                await renderSceneToPptx(pptxSlide, sceneResult.scene);
            } else if (slideElements?.[i]) {
                const { captureSlide } = await import('../pdfExporter');
                const imageData = await captureSlide(slideElements[i], 2.8);
                pptxSlide.addImage({
                    data: imageData,
                    x: 0,
                    y: 0,
                    w: '100%',
                    h: '100%',
                });
                renderedAsFallbackImage = true;
            } else {
                const adapter = getAdapter(slideData);
                await adapter.render(slideData, pptxSlide, colors, pptx);
            }
        } catch (error) {
            console.error(`Error rendering slide ${i + 1}:`, error);
            // Add error placeholder
            pptxSlide.background = { color: 'FFFFFF' };
            pptxSlide.addText(`Erreur lors du rendu de la slide "${slideData.title || i + 1}"`, {
                x: 1,
                y: 3,
                w: SLIDE_WIDTH - 2,
                h: 1,
                fontSize: 24,
                fontFace: 'Arial',
                color: 'FF0000',
                align: 'center',
            });
        }

        // === CUSTOM TEMPLATE ELEMENTS ===
        if (renderedAsFallbackImage) {
            continue;
        }

        const showBasePageNumber = presentation.templateOverlay?.footer?.showPageNumber !== undefined
            ? presentation.templateOverlay.footer.showPageNumber
            : true;
        addBaseSlideFooter(
            pptxSlide,
            typeof slideData.title === 'string' ? slideData.title : '',
            i + 1,
            showBasePageNumber,
            colors
        );

        if (presentation.templateOverlay) {
            const { logo, footer } = presentation.templateOverlay;
            const isCover = i === 0 || slideData.layout === 'cover';

            // 1. Logo Overlay
            if (logo && presentation.brandLogoUrl) {
                const shouldShow = isCover ? logo.showOnCover : logo.showOnContent;
                if (shouldShow) {
                    const { x, y, w, h } = getLogoPosition(logo.position, logo.size);
                    pptxSlide.addImage({
                        path: presentation.brandLogoUrl,
                        x, y, w, h
                    });
                }
            }

            // 2. Footer Overlay
            if (footer) {
                // Footer Text
                if (footer.text) {
                    pptxSlide.addText(footer.text, {
                        x: 0.5,
                        y: SLIDE_HEIGHT - 0.28,
                        w: SLIDE_WIDTH * 0.6,
                        h: 0.16,
                        fontSize: 8.5,
                        fontFace: 'Arial',
                        color: toHex(colors.text),
                        transparency: 38,
                        align: 'left',
                        margin: 0,
                    });
                }

                // Page Number (Override default if configured)
                if (footer.showPageNumber) {
                    pptxSlide.addText(`${i + 1} / ${processedSlides.length}`, {
                        x: SLIDE_WIDTH - 1.15,
                        y: SLIDE_HEIGHT - 0.28,
                        w: 0.72,
                        h: 0.16,
                        fontSize: 8.5,
                        fontFace: 'Arial',
                        color: toHex(colors.text),
                        align: 'right',
                        margin: 0,
                    });
                }
            }
        }
    }

    onProgress?.({
        current: processedSlides.length,
        total: processedSlides.length,
        status: 'generating',
        message: 'Génération du fichier PowerPoint...',
    });

    // Sanitize filename
    const sanitizedTitle = (presentation.title || 'presentation')
        .replace(/[^a-zA-Z0-9-_\s]/g, '')
        .trim();

    // Download file
    await pptx.writeFile({ fileName: `${sanitizedTitle}.pptx` });

    onProgress?.({
        current: processedSlides.length,
        total: processedSlides.length,
        status: 'complete',
        message: 'Export terminé !',
    });
};

/**
 * Exports presentation slides to PowerPoint as images (High Fidelity / Pixel Perfect)
 */
export const exportToPPTXWithImages = async (
    slideElements: HTMLElement[],
    title: string,
    onProgress?: ExportProgressCallback
): Promise<void> => {
    // Dynamic import to avoid circular dependencies if any, although here unneeded
    const { captureSlide } = await import('../pdfExporter');

    if (slideElements.length === 0) {
        throw new Error('No slides to export');
    }

    onProgress?.({
        current: 0,
        total: slideElements.length,
        status: 'preparing',
        message: 'Préparation du PowerPoint Haute Fidélité...',
    });

    const pptx = new pptxgen();
    pptx.author = 'SlideAI';
    pptx.title = title || 'Presentation';
    pptx.layout = 'LAYOUT_16x9'; // Standard 16:9

    // Ensure web fonts are loaded before captures for consistent text rendering.
    if (typeof document !== 'undefined' && 'fonts' in document) {
        await (document as any).fonts.ready;
    }

    // Explicitly set 1920x1080 layout logic? 
    // pptxgenjs default 16x9 is 10x5.625 inches. 
    // We want to map our 1920x1080 pixels to fit.
    // Best is to let pptx handle it, or we define custom layout if needed.
    // But adding image with x:0, y:0, w:'100%', h:'100%' should work.

    for (let i = 0; i < slideElements.length; i++) {
        const slide = slideElements[i];

        onProgress?.({
            current: i,
            total: slideElements.length,
            status: 'rendering',
            message: `Capture de la slide ${i + 1}/${slideElements.length}...`,
        });

        const pptxSlide = pptx.addSlide();

        try {
            // Capture in high quality to preserve readability once inside PowerPoint.
            const imageData = await captureSlide(slide, 2.8);

            pptxSlide.addImage({
                data: imageData,
                x: 0,
                y: 0,
                w: '100%',
                h: '100%',
            });

        } catch (error) {
            console.error(`Error capturing slide ${i + 1} for PPTX:`, error);
            pptxSlide.addText(`Erreur: Impossible de capturer la slide ${i + 1}`, { x: 1, y: 1, color: 'FF0000' });
        }

        // Small delay
        await new Promise(resolve => setTimeout(resolve, 100));
    }

    onProgress?.({
        current: slideElements.length,
        total: slideElements.length,
        status: 'generating',
        message: 'Génération du fichier PowerPoint...',
    });

    const sanitizedTitle = title.replace(/[^a-zA-Z0-9-_\s]/g, '').trim() || 'presentation';
    await pptx.writeFile({ fileName: `${sanitizedTitle}.pptx` });

    onProgress?.({
        current: slideElements.length,
        total: slideElements.length,
        status: 'complete',
        message: 'Export terminé !',
    });
};
