// src/lib/export/pptx/pptxExporter.ts
// PowerPoint export using PptxGenJS with layout adapters

import pptxgen from 'pptxgenjs';
import { getAdapter } from './adapters';
import { PresentationData, ColorPalette, SLIDE_WIDTH, SLIDE_HEIGHT, toHex } from './types';
import { ExportProgressCallback } from '../types';

// Default color palette if none provided
const DEFAULT_COLORS: ColorPalette = {
    primary: '#2563EB',
    secondary: '#7C3AED',
    accent: '#2563EB',
    bg: '#FFFFFF',
    text: '#0F172A',
};

/**
 * Export presentation to PowerPoint format
 * 
 * @param presentation - Presentation data including slides and theme
 * @param onProgress - Optional progress callback
 */
export const exportToPPTX = async (
    presentation: PresentationData,
    onProgress?: ExportProgressCallback
): Promise<void> => {
    if (!presentation.slides || presentation.slides.length === 0) {
        throw new Error('No slides to export');
    }

    onProgress?.({
        current: 0,
        total: presentation.slides.length,
        status: 'preparing',
        message: 'Initialisation du PowerPoint...',
    });

    // Create new presentation
    const pptx = new pptxgen();

    // Set presentation properties
    pptx.author = 'SlideAI';
    pptx.title = presentation.title || 'Presentation';
    pptx.subject = 'Generated by SlideAI';
    pptx.company = 'SlideAI';

    // Define 16:9 layout
    pptx.defineLayout({
        name: 'SLIDEAI_16x9',
        width: SLIDE_WIDTH,
        height: SLIDE_HEIGHT,
    });
    pptx.layout = 'SLIDEAI_16x9';

    // Get color palette
    const colors = presentation.colorScheme || DEFAULT_COLORS;

    // Process each slide
    for (let i = 0; i < presentation.slides.length; i++) {
        const slideData = presentation.slides[i];

        onProgress?.({
            current: i,
            total: presentation.slides.length,
            status: 'rendering',
            message: `Création de la slide ${i + 1}/${presentation.slides.length}...`,
        });

        // Create new slide
        const pptxSlide = pptx.addSlide();

        // Get appropriate adapter
        const adapter = getAdapter(slideData);

        // Render slide using adapter
        try {
            await adapter.render(slideData, pptxSlide, colors, pptx);
        } catch (error) {
            console.error(`Error rendering slide ${i + 1}:`, error);
            // Add error placeholder
            pptxSlide.background = { color: 'FFFFFF' };
            pptxSlide.addText(`Erreur lors du rendu de la slide "${slideData.title || i + 1}"`, {
                x: 1,
                y: 3,
                w: SLIDE_WIDTH - 2,
                h: 1,
                fontSize: 24,
                fontFace: 'Arial',
                color: 'FF0000',
                align: 'center',
            });
        }

        // Add slide number
        pptxSlide.addText(String(i + 1), {
            x: SLIDE_WIDTH - 0.8,
            y: SLIDE_HEIGHT - 0.5,
            w: 0.5,
            h: 0.3,
            fontSize: 10,
            fontFace: 'Arial',
            color: toHex(colors.text),
            align: 'right',
        });
    }

    onProgress?.({
        current: presentation.slides.length,
        total: presentation.slides.length,
        status: 'generating',
        message: 'Génération du fichier PowerPoint...',
    });

    // Sanitize filename
    const sanitizedTitle = (presentation.title || 'presentation')
        .replace(/[^a-zA-Z0-9-_\s]/g, '')
        .trim();

    // Download file
    await pptx.writeFile({ fileName: `${sanitizedTitle}.pptx` });

    onProgress?.({
        current: presentation.slides.length,
        total: presentation.slides.length,
        status: 'complete',
        message: 'Export terminé !',
    });
};
