import { useState, useEffect, useRef } from "react";
import { useParams, useSearchParams, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ModernSlideRenderer } from "@/components/slides/ModernSlideRenderer";
import { examples } from "@/data/examples";
import { api } from "@/lib/api";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/contexts/AuthContext";
import {
  Loader2,
  Download,
  Home,
  ChevronLeft,
  ChevronRight,
  Layout,
  Maximize2,
  Minimize2,
  Play,
  Save,
  Share2,
  AlertCircle,
  Sparkles,
  Trash2,
  GripVertical
} from "lucide-react";
import { Reorder, AnimatePresence } from "framer-motion";
import { PresentationBuilderLoader } from "@/components/layout/PresentationBuilderLoader";

import { AddElementMenu } from "@/components/editor/AddElementMenu";
import { PropertiesPanel, SelectedElement } from "@/components/editor/PropertiesPanel";
import { ShareDialog } from "@/components/editor/ShareDialog";
import { RegenerateSlideDialog } from "@/components/editor/RegenerateSlideDialog";
import { LayoutSwitcher } from "@/components/editor/LayoutSwitcher";
import { ColorPaletteDialog } from "@/components/editor/ColorPaletteDialog";
import { ExportDialog } from "@/components/editor/ExportDialog";
import { Wand2, Palette } from "lucide-react";



// Helper to adapt API deck format to frontend format
const adaptDeck = (deck: any) => {
  // If deck is coming from Supabase, the 'slides' property actually contains the FULL deck object
  // generated by the worker (which includes slides, theme, colorPalette, etc.)
  const rootData = deck.slides?.slides ? deck.slides : deck;
  const slideItems = deck.slides?.slides || deck.slides || [];

  return {
    id: deck.id || "generated",
    title: deck.title || rootData.title,
    subtitle: deck.subtitle || rootData.subtitle,
    thumbnail: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&q=80",
    lastModified: new Date().toISOString(),
    slides: slideItems.map((s: any, index: number) => ({
      id: s.id || `slide-${index}`,
      type: s.type || s.layout || "content",
      title: s.title,
      subtitle: s.subtitle || s.content?.subtitle,
      layout: s.layout || "title-top-bullets-bottom",

      // Background image from Unsplash
      backgroundImage: s.backgroundImage,
      imageSearchQuery: s.imageSearchQuery, // Used by some layouts as fallback

      // Legacy content fields
      // Legacy content fields
      bullets: s.bullets || s.content?.bullets || [],
      quote: s.quote || s.content?.quote,
      metrics: s.metrics || s.content?.metrics,
      columns: s.columns || s.content?.columns,
      description: s.description || s.content?.description,
      benefits: s.benefits || s.content?.benefits,

      // NEW: Rich content types
      chart: s.chart || s.content?.chart,
      table: s.table || s.content?.table,
      timeline: s.timeline || s.content?.timeline,
      infographic: s.infographic || s.content?.infographic,
      comparison: s.comparison || s.content?.comparison,
      stats: s.stats || s.content?.stats,
      items: s.items || s.content?.items,
      text: s.text || s.content?.text,

      // Layout variation selection (user choice from LayoutSwitcher)
      variation: s.variation,

      // Pass through the entire content object as fallback
      content: s.content,

      // Illustration handling
      illustration: s.illustration || {
        type: "icon",
        iconName: "Sparkles",
        url: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&q=80"
      },

      notes: s.notes || "",
    })),
    theme: deck.theme || rootData.theme || "startup-pitch",
    themeConfig: deck.themeConfig || rootData.themeConfig,
    colorScheme: deck.colorPalette || deck.colorScheme || rootData.colorPalette || rootData.colorScheme,
  };
};

// Map project IDs to examples for dev/test
const projectMap: Record<string, any> = {
  "deck-1": examples[0],
  "deck-2": examples[1],
  "deck-3": examples[2],
};

export default function Editor() {
  const { traceId } = useParams();
  const [searchParams] = useSearchParams();
  const presentationId = searchParams.get("id"); // Get ?id=UUID from URL
  const { toast } = useToast();

  // Refs
  const editorContainerRef = useRef<HTMLDivElement>(null);
  const slideContainerRef = useRef<HTMLDivElement>(null);

  // States
  const [currentProject, setCurrentProject] = useState<any>(null);
  const [selectedSlide, setSelectedSlide] = useState(0);
  const [selectedElement, setSelectedElement] = useState<SelectedElement | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isExporting, setIsExporting] = useState(false);
  const [status, setStatus] = useState<string>("idle");
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [slideScale, setSlideScale] = useState(1);
  const [error, setError] = useState<string | null>(null);
  const [isExportDialogOpen, setIsExportDialogOpen] = useState(false);
  const [accessToken, setAccessToken] = useState<string | null>(null);

  // Get access token on mount
  useEffect(() => {
    const getToken = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (session) setAccessToken(session.access_token);
    };
    getToken();
  }, []);

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // Don't trigger if editing text
      if (e.target instanceof HTMLTextAreaElement || e.target instanceof HTMLInputElement) return;

      if (!currentProject) return;

      if (e.key === "ArrowRight" || e.key === "ArrowDown" || e.key === " ") {
        if (selectedSlide < currentProject.slides.length - 1) {
          setSelectedSlide(prev => prev + 1);
          setSelectedElement(null);
        }
      } else if (e.key === "ArrowLeft" || e.key === "ArrowUp") {
        if (selectedSlide > 0) {
          setSelectedSlide(prev => prev - 1);
          setSelectedElement(null);
        }
      } else if (e.key === "Escape") {
        if (selectedElement) {
          setSelectedElement(null);
        } else if (document.fullscreenElement) {
          document.exitFullscreen();
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [currentProject, selectedSlide, selectedElement]);

  // Handle Fullscreen events
  useEffect(() => {
    const handleFullscreenChange = () => {
      setIsFullscreen(!!document.fullscreenElement);
    };
    document.addEventListener("fullscreenchange", handleFullscreenChange);
    return () => document.removeEventListener("fullscreenchange", handleFullscreenChange);
  }, []);

  // Scale slide to fit container
  useEffect(() => {
    const updateScale = () => {
      if (!slideContainerRef.current) return;

      const container = slideContainerRef.current;
      const { width, height } = container.getBoundingClientRect();

      // Target 1920x1080
      const targetWidth = 1920;
      const targetHeight = 1080;

      // Add padding calculation - account for navigation buttons and breathing room
      const horizontalPadding = isFullscreen ? 0 : 160; // Space for nav buttons (left/right arrows)
      const verticalPadding = isFullscreen ? 0 : 120;   // Space for bottom pill and breathing room

      const availableWidth = width - horizontalPadding;
      const availableHeight = height - verticalPadding;

      const scaleX = availableWidth / targetWidth;
      const scaleY = availableHeight / targetHeight;

      // Cap the scale to prevent overflow - max 0.55 for non-fullscreen
      const maxScale = isFullscreen ? 1 : 0.55;
      setSlideScale(Math.min(scaleX, scaleY, maxScale));
    };

    const observer = new ResizeObserver(updateScale);
    if (slideContainerRef.current) {
      observer.observe(slideContainerRef.current);
    }

    // Small delay to ensure layout is stable
    setTimeout(updateScale, 100);

    window.addEventListener('resize', updateScale);

    return () => {
      observer.disconnect();
      window.removeEventListener('resize', updateScale);
    };
  }, [isFullscreen, isLoading]);

  // Data Fetching
  useEffect(() => {
    setError(null);

    // === MODE 1: Fetch by presentation ID via API ===
    if (presentationId) {
      const fetchFromAPI = async () => {
        setIsLoading(true);
        const { data: { session } } = await supabase.auth.getSession();
        if (!session) {
          setError("Connexion requise");
          setIsLoading(false);
          return;
        }
        setAccessToken(session.access_token);
        try {
          const data = await api.getPresentation(presentationId, session.access_token);
          const adapted = adaptDeck({
            id: data.id,
            title: data.title,
            slides: data.slides,
            theme: data.theme,
          });
          setCurrentProject(adapted);
          setIsLoading(false);
        } catch (err: any) {
          console.error("API fetch error:", err);
          setError(err.message || "Erreur lors du chargement");
          setIsLoading(false);
        }
      };
      fetchFromAPI();
      return;
    }

    // === MODE 2: Mock data for dev/test ===
    if (traceId && projectMap[traceId]) {
      setCurrentProject(projectMap[traceId]);
      setIsLoading(false);
      return;
    }

    // === MODE 3: Poll job status (generation in progress) ===
    if (traceId) {
      const pollStatus = async () => {
        try {
          const res = await api.getJobStatus(traceId);
          setStatus(res.status);

          if (res.status === "succeeded" && res.deck) {
            const realId = res.deck.id;

            // Update URL without reloading
            if (realId && realId !== "generated") {
              const newUrl = new URL(window.location.href);
              newUrl.searchParams.delete("traceId");
              newUrl.searchParams.set("id", realId);
              window.history.replaceState({}, "", newUrl.toString());
            }

            setCurrentProject(adaptDeck(res.deck));
            setIsLoading(false);
            return true; // Stop polling
          } else if (res.status === "failed") {
            setIsLoading(false);
            setError(res.error || "Une erreur est survenue");
            return true; // Stop polling
          } else {
            // Still processing
            setIsLoading(true);
          }
          return false;
        } catch (err) {
          console.error("Polling error:", err);
          return false;
        }
      };

      // Poll immediately
      pollStatus();

      // Setup interval
      const interval = setInterval(async () => {
        const stop = await pollStatus();
        if (stop) clearInterval(interval);
      }, 2000);

      return () => clearInterval(interval);
    }

    // === MODE 4: No ID provided - fetch latest from Supabase ===
    const fetchLatest = async () => {
      setIsLoading(true);
      try {
        const { data, error: dbError } = await supabase
          .from('presentations')
          .select('*')
          .order('created_at', { ascending: false })
          .limit(1)
          .single();

        if (dbError || !data) {
          setError("Aucune présentation trouvée");
          setIsLoading(false);
          return;
        }

        const adapted = adaptDeck({
          id: data.id,
          title: data.title,
          slides: data.slides,
          theme: data.theme,
        });
        setCurrentProject(adapted);
        setIsLoading(false);
      } catch (err: any) {
        console.error("Supabase fetch error:", err);
        setError("Erreur lors du chargement");
        setIsLoading(false);
      }
    };

    fetchLatest();
  }, [traceId, presentationId, toast]);

  const toggleFullscreen = () => {
    if (!editorContainerRef.current) return;

    if (!document.fullscreenElement) {
      editorContainerRef.current.requestFullscreen().catch(err => {
        console.error(`Error attempting to enable full-screen mode: ${err.message}`);
      });
    } else {
      document.exitFullscreen();
    }
  };



  const handleElementSelect = (element: any) => {
    // Add slide index to ID to make it unique across deck
    const fullId = `${selectedSlide}-${element.id}`;
    setSelectedElement({ ...element, id: fullId });
  };

  // Helper helper to update nested object immutably
  const updateDeep = (obj: any, pathParts: string[], value: any): any => {
    // If we've reached the end of the path, return the value
    if (pathParts.length === 0) return value;

    const [head, ...tail] = pathParts;
    const index = parseInt(head);
    const isArrayIndex = !isNaN(index);

    // If strict array syntax was used in path splitting, we can know if it's an array
    // But simple inference: if valid integer, treat as array access if obj is array or empty

    const currentVal = obj || {};
    const isCurrentArray = Array.isArray(currentVal);

    // Create shallow copy
    const copy = isCurrentArray ? [...currentVal] : { ...currentVal };

    // recurse
    copy[head] = updateDeep(currentVal[head], tail, value);

    return copy;
  };

  const handleElementUpdate = (path: string, value: any) => {
    if (!currentProject) return;

    // Split path: 'content.columns[0].title' -> ['content', 'columns', '0', 'title']
    // Regex matches . or [ or ] (but filter out empty strings from ] split)
    const pathParts = path.replace(/\]/g, '').split(/[\.\[]/);

    const newProject = { ...currentProject };
    const newSlides = [...newProject.slides];

    // Update generic slide state recursively
    // We treat 'newSlides[selectedSlide]' as the root
    newSlides[selectedSlide] = updateDeep(newSlides[selectedSlide], pathParts, value);

    // Also update local selected element for immediate feedback
    if (selectedElement) {
      setSelectedElement({ ...selectedElement, value });
    }

    newProject.slides = newSlides;
    setCurrentProject(newProject);
  };

  const handleTableAction = (action: 'add-row' | 'delete-row', cellPath: string) => {
    if (!currentProject) return;

    // Regex to get row index
    const rowMatch = cellPath.match(/\[(\d+)\]\[\d+\]$/);
    const targetRowIdx = rowMatch ? parseInt(rowMatch[1]) : -1;

    // 1. Identify which rows array we are dealing with.
    const rowsPathString = cellPath.replace(/\[\d+\]\[\d+\]$/, '');

    // Safety check
    if (rowsPathString === cellPath) {
      console.warn("Could not determine rows path from", cellPath);
      return;
    }

    // 2. Locate the rows array
    const pathParts = rowsPathString.replace(/\]/g, '').split(/[\.\[]/);

    const slides = [...currentProject.slides];
    const slide = slides[selectedSlide];

    let current: any = slide;
    let valid = true;
    for (const part of pathParts) {
      if (current && current[part] !== undefined) {
        current = current[part];
      } else {
        valid = false;
        break;
      }
    }
    const rows = current;

    if (valid && Array.isArray(rows) && rows.length > 0) {
      if (action === 'delete-row') {
        if (targetRowIdx === -1) return;

        if (rows.length <= 1) {
          toast({ title: "Action impossible", description: "Le tableau doit contenir au moins une ligne.", variant: "destructive" });
          return;
        }

        const newRows = rows.filter((_, i) => i !== targetRowIdx);
        const updatedSlide = updateDeep(slide, pathParts, newRows);
        slides[selectedSlide] = updatedSlide;
        setCurrentProject({ ...currentProject, slides });

        toast({ title: "Ligne supprimée", description: "La ligne a été supprimée." });
        setSelectedElement(null);
        return;
      }

      const colCount = rows[0].length;
      const newRow = Array(colCount).fill("Nouveau");

      const newRows = [...rows, newRow];

      // Update state
      const updatedSlide = updateDeep(slide, pathParts, newRows);
      slides[selectedSlide] = updatedSlide;

      setCurrentProject({ ...currentProject, slides });

      toast({
        title: "Ligne ajoutée",
        description: "Une nouvelle ligne a été ajoutée au tableau.",
      });
    } else {
      console.error("Failed to find valid rows array at", rowsPathString, rows);
    }
  };




  const handleAddElement = (type: 'text' | 'image' | 'shape') => {
    if (!currentProject) return;

    const newProject = { ...currentProject };
    const newSlides = [...newProject.slides];
    const slide = { ...newSlides[selectedSlide] };

    // Ensure elements array exists
    const elements = slide.elements ? [...slide.elements] : [];

    const newId = `el-${Date.now()}`;
    const newElement = {
      id: newId,
      type: type,
      x: 35,
      y: 35,
      width: type === 'text' ? 30 : 25,
      height: type === 'text' ? 10 : 25,
      rotation: 0,
      opacity: 1,
      content: type === 'text' ? 'New Text Block' : 'https://source.unsplash.com/random/400x300',
      value: type === 'text' ? 'New Text Block' : 'https://source.unsplash.com/random/400x300',
      path: `elements[${elements.length}]`,
      label: type === 'text' ? 'Text Box' : 'Image',
      style: {
        fontSize: '1.5rem',
        textAlign: 'left', // Default align
        color: currentProject.colorScheme?.text || '#000000',
        fontWeight: 'normal'
      }
    };

    elements.push(newElement);
    slide.elements = elements;

    newSlides[selectedSlide] = slide;
    newProject.slides = newSlides;
    setCurrentProject(newProject);

    // Select the new element immediately
    // Note: handleElementSelect expects raw element, it adds prefix
    handleElementSelect(newElement);
  };

  const handleSave = async () => {
    if (!currentProject || !accessToken) return;
    try {
      await api.savePresentation(currentProject.id, { slides: currentProject.slides }, accessToken);
      toast({ title: "Sauvegardé", description: "Vos modifications sont enregistrées." });
    } catch (e: any) {
      console.error("Save error:", e);
      toast({ title: "Erreur", description: e.message || "Échec de la sauvegarde.", variant: "destructive" });
    }
  };

  const handleDeleteSlide = (index: number, e: React.MouseEvent) => {
    e.stopPropagation(); // Prevent slide selection when clicking delete

    if (!currentProject) return;

    // Prevent deleting the last slide
    if (currentProject.slides.length <= 1) {
      toast({
        title: "Action impossible",
        description: "La présentation doit contenir au moins une slide.",
        variant: "destructive"
      });
      return;
    }

    const newProject = { ...currentProject };
    const newSlides = [...newProject.slides];

    // Remove the slide
    newSlides.splice(index, 1);
    newProject.slides = newSlides;

    // Update local state
    setCurrentProject(newProject);

    // Adjust selection if needed
    if (selectedSlide >= newSlides.length) {
      setSelectedSlide(newSlides.length - 1);
    } else if (selectedSlide === index) {
      // If we deleted the current slide, we're already at the correct index for the next one
      // unless we were at the end, which is handled above.
      // But we should probably just keep the index unless it's out of bounds.
    }

    setSelectedElement(null);
    toast({ title: "Slide supprimée", description: "La diapositive a été supprimée." });
  };

  const handleReorderSlides = (newSlides: any[]) => {
    if (!currentProject) return;

    // Find where the selected slide went
    const selectedSlideId = currentProject.slides[selectedSlide].id;
    const newIndex = newSlides.findIndex((s: any) => s.id === selectedSlideId);

    setCurrentProject({
      ...currentProject,
      slides: newSlides
    });

    if (newIndex !== -1) {
      setSelectedSlide(newIndex);
    }
  };

  // Loading Screen
  if (isLoading || !currentProject) {
    if (error) {
      return (
        <div className="min-h-screen flex flex-col items-center justify-center bg-background">
          <div className="text-center space-y-6 p-12 rounded-[2rem] bg-surface/50 backdrop-blur-xl border border-border shadow-2xl">
            <div className="relative inline-block">
              <AlertCircle className="h-16 w-16 text-destructive relative z-10" />
            </div>
            <div className="space-y-2">
              <h2 className="text-2xl font-bold text-foreground tracking-tight">Oops!</h2>
              <p className="text-muted-foreground">{error}</p>
              <Link to="/" className="inline-block mt-4 px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors">
                Retour à l'accueil
              </Link>
            </div>
          </div>
        </div>
      );
    }

    return (
      <div className="min-h-screen flex items-center justify-center bg-background overflow-hidden">
        <PresentationBuilderLoader status={status} />
      </div>
    );
  }

  return (
    <div
      ref={editorContainerRef}
      className="h-screen flex flex-col overflow-hidden font-sans bg-background text-foreground selection:bg-accent selection:text-foreground"
    >
      {/* 1. Header (Hidden in Fullscreen) */}
      {!isFullscreen && (
        <div className="h-16 flex items-center justify-between px-6 border-b border-border bg-background/90 backdrop-blur-md z-50 shadow-sm shrink-0">
          <div className="flex items-center space-x-6">
            <Link to="/" className="group flex items-center justify-center w-10 h-10 rounded-xl hover:bg-muted transition-all">
              <Home className="h-5 w-5 text-muted-foreground group-hover:text-foreground transition-colors" />
            </Link>

            <div className="h-6 w-px bg-[#E6E6E0]"></div>

            <div className="flex flex-col justify-center">
              <Input
                defaultValue={currentProject.title}
                readOnly
                className="h-6 text-sm font-semibold border-0 bg-transparent p-0 focus-visible:ring-0 w-64 text-foreground hover:text-primary transition-colors cursor-default"
              />
              <span className="text-[10px] font-medium text-muted-foreground flex items-center gap-2 mt-0.5">
                <span className="w-1.5 h-1.5 rounded-full bg-[#10B981]"></span>
                Ready to Present
              </span>
            </div>
          </div>

          <div className="flex items-center space-x-4">
            {/* Removed Search, Undo/Redo, AI Assistant */}

            <Button
              onClick={toggleFullscreen}
              className="h-9 px-5 rounded-lg bg-primary hover:bg-[#1F1F1F] text-white shadow-lg shadow-primary/20 border border-border font-medium transition-all hover:scale-105"
            >
              <Play className="h-3.5 w-3.5 mr-2 fill-current" />
              Diaporama
            </Button>


            <div className="flex items-center gap-2">
              <Button variant="ghost" onClick={handleSave} title="Sauvegarder">
                <Save className="w-4 h-4" />
              </Button>
              {currentProject && accessToken && (
                <ShareDialog
                  presentationId={currentProject.id}
                  accessToken={accessToken}
                />
              )}
              {currentProject && accessToken && (
                <ColorPaletteDialog
                  presentationId={currentProject.id}
                  accessToken={accessToken}
                  currentPalette={currentProject.colorScheme}
                  onSuccess={(newPalette) => {
                    // Update the local colorScheme
                    setCurrentProject({ ...currentProject, colorScheme: newPalette });
                  }}
                >
                  <Button variant="ghost" title="Modifier la palette de couleurs">
                    <Palette className="w-4 h-4" />
                  </Button>
                </ColorPaletteDialog>
              )}
              <AddElementMenu onAdd={handleAddElement} />
              <Button variant="outline" onClick={() => setIsExportDialogOpen(true)}>
                <Download className="w-4 h-4 mr-2" />
                Export
              </Button>
            </div>
          </div>
        </div>
      )}

      <div className="flex-1 flex overflow-hidden">

        {/* 2. Vertical Timeline (Left Sidebar) - Now displays all slides */}
        {!isFullscreen && (
          <div className="w-64 flex flex-col border-r border-border bg-surface/50 backdrop-blur-sm z-30">
            <div className="p-4 border-b border-border flex items-center justify-between bg-surface/80">
              <span className="text-xs font-bold tracking-widest uppercase text-muted-foreground">Slides</span>
              <span className="text-[10px] bg-muted px-1.5 py-0.5 rounded text-muted-foreground">{currentProject.slides.length}</span>
            </div>

            <div className="flex-1 overflow-y-auto overflow-x-hidden p-4 space-y-4 custom-scrollbar">
              <Reorder.Group
                axis="y"
                values={currentProject.slides}
                onReorder={handleReorderSlides}
                className="space-y-4"
              >
                {currentProject.slides.map((slide: any, idx: number) => (
                  <Reorder.Item
                    key={slide.id}
                    value={slide}
                    className="relative"
                  >
                    <div
                      onClick={() => { setSelectedSlide(idx); setSelectedElement(null); }}
                      className={`group relative cursor-pointer outline-none touch-none`}
                    >
                      {/* Slide Number Indicator */}
                      <div className="absolute -left-2 top-1/2 -translate-y-1/2 w-1 h-8 bg-primary rounded-r-full transition-all duration-300 origin-left scale-x-0 group-hover:scale-x-100 mb-1" style={{ opacity: selectedSlide === idx ? 1 : undefined, transform: selectedSlide === idx ? 'scaleX(1)' : undefined }}></div>

                      <div className={`relative aspect-video w-full rounded-lg overflow-hidden border transition-all duration-200 ${selectedSlide === idx
                        ? "border-primary ring-2 ring-primary/10 shadow-lg scale-[1.02]"
                        : "border-border hover:border-primary/50 hover:shadow-md"
                        }`}>
                        <div className="w-full h-full bg-surface relative pointer-events-none">
                          {/* Scaled preview of the slide */}
                          <div className="absolute top-0 left-0 w-[1920px] h-[1080px] origin-top-left" style={{ transform: `scale(${220 / 1920})` /* Approx scale for sidebar width */ }}>
                            <ModernSlideRenderer
                              slide={slide}
                              theme={currentProject.theme}
                              colorPalette={currentProject.colorScheme}
                              className="w-full h-full"
                            />
                          </div>
                        </div>

                        {/* Drag Handle Overlay */}
                        <div className="absolute inset-0 bg-black/0 group-hover:bg-black/5 transition-colors flex justify-end gap-1 p-2 opacity-0 group-hover:opacity-100">
                          {/* Regenerate Button */}
                          {accessToken && (
                            <RegenerateSlideDialog
                              presentationId={currentProject.id}
                              slideIndex={idx}
                              slideTitle={slide.title}
                              accessToken={accessToken}
                              onSuccess={(newSlide) => {
                                // Replace the slide at this index
                                const newSlides = [...currentProject.slides];
                                newSlides[idx] = {
                                  ...newSlide,
                                  id: newSlide.id || `slide-${idx}-${Date.now()}`,
                                  bullets: newSlide.bullets || newSlide.content?.bullets || [],
                                  chart: newSlide.chart || newSlide.content?.chart,
                                  table: newSlide.table || newSlide.content?.table,
                                  timeline: newSlide.timeline || newSlide.content?.timeline,
                                  infographic: newSlide.infographic || newSlide.content?.infographic,
                                  comparison: newSlide.comparison || newSlide.content?.comparison,
                                  stats: newSlide.stats || newSlide.content?.stats,
                                  items: newSlide.items || newSlide.content?.items,
                                  content: newSlide.content,
                                };
                                setCurrentProject({ ...currentProject, slides: newSlides });
                              }}
                            >
                              <Button
                                variant="secondary"
                                size="icon"
                                className="h-6 w-6 rounded shadow-sm opacity-0 group-hover:opacity-100 transition-opacity z-10"
                                onClick={(e) => e.stopPropagation()}
                                title="Régénérer la slide"
                              >
                                <Wand2 className="h-3 w-3" />
                              </Button>
                            </RegenerateSlideDialog>
                          )}
                          <Button
                            variant="destructive"
                            size="icon"
                            className="h-6 w-6 rounded shadow-sm opacity-0 group-hover:opacity-100 transition-opacity z-10"
                            onClick={(e) => handleDeleteSlide(idx, e)}
                            title="Supprimer la slide"
                          >
                            <Trash2 className="h-3 w-3" />
                          </Button>
                        </div>

                        {/* Drag Indicator */}
                        <div className="absolute left-2 top-2 p-1 bg-background/50 backdrop-blur rounded opacity-0 group-hover:opacity-100 transition-opacity cursor-grab active:cursor-grabbing">
                          <GripVertical className="h-3 w-3 text-foreground/50" />
                        </div>
                      </div>

                      <div className="mt-1.5 flex items-center justify-between px-1">
                        <span className={`text-[10px] font-medium transition-colors ${selectedSlide === idx ? "text-primary" : "text-muted-foreground"}`}>
                          {idx + 1}. {slide.title || "Untitled Slide"}
                        </span>
                      </div>
                    </div>
                  </Reorder.Item>
                ))}
              </Reorder.Group>

              <div className="h-10"></div> {/* Spacer */}
            </div>
          </div>
        )}

        {/* 3. Main Canvas Area */}
        <div
          ref={slideContainerRef}
          className={`flex-1 relative overflow-hidden flex items-center justify-center ${isFullscreen ? 'bg-black' : 'bg-background/50 p-8'}`}
        >
          {/* Background Effects (only when not fullscreen) */}
          {!isFullscreen && (
            <div className="absolute inset-0 pointer-events-none">
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-primary/5 rounded-full blur-[80px]"></div>
              <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-[0.02]"></div>
            </div>
          )}

          {/* Render Slide - Wrapper ensures the scaled slide doesn't overflow */}
          <div
            style={{
              width: `${1920 * slideScale}px`,
              height: `${1080 * slideScale}px`,
            }}
          >
            <div
              className={`relative shadow-2xl ${isFullscreen ? '' : 'rounded-xl ring-1 ring-black/5'}`}
              style={{
                width: '1920px',
                height: '1080px',
                transform: `scale(${slideScale})`,
                transformOrigin: 'top left',
              }}
            >
              <ModernSlideRenderer
                slide={currentProject.slides[selectedSlide]}
                theme={currentProject.theme}
                colorPalette={currentProject.colorScheme}
                className="w-full h-full"
                onElementSelect={isFullscreen ? undefined : handleElementSelect}
                selectedElementId={!isFullscreen && selectedElement ? selectedElement.id.split('-').slice(1).join('-') : null}
              />
            </div>
          </div>

          {/* Navigation Controls (Floating) */}
          {!isFullscreen && (
            <>
              <div className="absolute left-8 top-1/2 -translate-y-1/2">
                <Button
                  onClick={() => selectedSlide > 0 && setSelectedSlide(selectedSlide - 1)}
                  disabled={selectedSlide === 0}
                  variant="ghost"
                  size="icon"
                  className="h-12 w-12 rounded-full bg-background/80 backdrop-blur shadow-lg hover:bg-primary hover:text-white transition-all disabled:opacity-0"
                >
                  <ChevronLeft className="h-6 w-6" />
                </Button>
              </div>

              <div className="absolute right-8 top-1/2 -translate-y-1/2">
                <Button
                  onClick={() => selectedSlide < currentProject.slides.length - 1 && setSelectedSlide(selectedSlide + 1)}
                  disabled={selectedSlide === currentProject.slides.length - 1}
                  variant="ghost"
                  size="icon"
                  className="h-12 w-12 rounded-full bg-background/80 backdrop-blur shadow-lg hover:bg-primary hover:text-white transition-all disabled:opacity-0"
                >
                  <ChevronRight className="h-6 w-6" />
                </Button>
              </div>

              {/* Bottom Info Pill */}
              <div className="absolute bottom-6 left-1/2 -translate-x-1/2 px-4 py-2 rounded-full bg-background/80 backdrop-blur-md text-xs font-medium shadow-sm border border-border flex items-center gap-3 text-muted-foreground cursor-default">
                <span>Slide {selectedSlide + 1} of {currentProject.slides.length}</span>
              </div>
            </>
          )}
        </div>

        {/* 4. Right Sidebar: Layout Switcher or Properties */}
        {!isFullscreen && (
          <div className="w-[280px] border-l border-border bg-surface/50 backdrop-blur-sm z-30 flex flex-col shrink-0">
            {selectedElement ? (
              <PropertiesPanel
                element={selectedElement}
                onUpdate={handleElementUpdate}
                onTableAction={handleTableAction}
                onClose={() => setSelectedElement(null)}
              />
            ) : (
              <LayoutSwitcher
                currentSlide={currentProject.slides[selectedSlide]}
                theme={currentProject.theme}
                colors={currentProject.colorScheme}
                onUpdateSlide={(newSlideData) => {
                  const newSlides = [...currentProject.slides];
                  // Merge new layout data but keep key IDs if needed, though partial update is usually handled by adapter
                  newSlides[selectedSlide] = {
                    ...newSlides[selectedSlide],
                    ...newSlideData
                  };
                  setCurrentProject({ ...currentProject, slides: newSlides });
                }}
              />
            )}
          </div>
        )}

      </div>

      {/* Export Dialog */}
      <ExportDialog
        open={isExportDialogOpen}
        onOpenChange={setIsExportDialogOpen}
        presentation={currentProject}
      />
    </div>
  );
}

