
import * as fs from 'fs';
import * as path from 'path';

const examplesPath = path.join(process.cwd(), 'src/data/examples.ts');
const newExamplePath = path.join(process.cwd(), 'exported_arca.json');

const currentContent = fs.readFileSync(examplesPath, 'utf-8');
const newExampleData = JSON.parse(fs.readFileSync(newExamplePath, 'utf-8'));

// Format the new example
const newExample = {
    title: newExampleData.title,
    prompt: "Crée une présentation pour Studio Arca, un cabinet d'architecture spécialisé dans le design biophilique, l'innovation durable et l'intégration de la nature dans les espaces urbains.",
    theme: newExampleData.slides.theme || newExampleData.theme || "creative-portfolio",
    colorPalette: newExampleData.slides.colorPalette || newExampleData.colorPalette,
    slides: newExampleData.slides.slides || newExampleData.slides
};

// We will reconstruct the file instead of regex replacement to be safer
// Find the start of the array
const startMarker = "export const examples: Example[] = [";
const startIndex = currentContent.indexOf(startMarker);

if (startIndex === -1) {
    console.error("Could not find examples array start");
    process.exit(1);
}

// Find the second example (Lancement Strategique) to preserve it
// We assume it starts after the first object closure "},"
// This is a bit brittle but we know the structure:
// [ {Studio Arca}, {Lancement Strategique} ]

// Let's just hardcode: we keep the second example if it exists
// Actually, safer approach: Read the file, find the second example by title if possible, or just replace the first element of the array.

// Since we know the file structure is correct TS, let's use a split approach
const parts = currentContent.split(startMarker);
const arrayContent = parts[1];

// This is complex to parse with regex/split robustly without AST.
// Fallback: We know "Lancement Stratégique" is the second example.
// We will look for that string to find where the second example starts.

const secondExampleMarker = '"title": "Lancement Stratégique SlideAI B2B Europe 2026"';
const secondExampleIndex = arrayContent.indexOf(secondExampleMarker);

let newFileContent = "";

if (secondExampleIndex !== -1) {
    // We found the second example. The first example ends before this.
    // We need to find the start of the second example object "  {"
    const secondExampleStart = arrayContent.lastIndexOf("{", secondExampleIndex);
    // And the comma before it
    const commaIndex = arrayContent.lastIndexOf(",", secondExampleStart);

    // Everything after commaIndex (inclusive of comma) is the rest of the array
    const restOfArray = arrayContent.substring(commaIndex);

    // Construct new content
    newFileContent = `${parts[0]}${startMarker}
  ${JSON.stringify(newExample, null, 2)}${restOfArray}`;

} else {
    // Only one example or unexpected structure? 
    // If we can't find the second example, maybe we just replace the whole array with [NewExample] 
    // BUT we don't want to lose the second example if it's there but title changed.

    // Let's assume for now we are replacing the FIRST element.
    // If the file was just generated by us, it has 2 elements.
    console.log("Could not find second example marker, attempting to preserve structure...");
    // Fallback: Replace up to the first "  }," which closes the first object
    // This relies on indentation being 2 spaces
    const firstObjectEnd = arrayContent.indexOf("\n  },");
    if (firstObjectEnd === -1) {
        console.error("Could not find end of first object");
        process.exit(1);
    }

    const restOfArray = arrayContent.substring(firstObjectEnd + 5); // +5 for \n  },

    newFileContent = `${parts[0]}${startMarker}
  ${JSON.stringify(newExample, null, 2)},${restOfArray}`;
}

fs.writeFileSync(examplesPath, newFileContent, 'utf-8');
console.log("Successfully updated Studio Arca example in examples.ts");
